export const GENRES = [
  { value: "None", label: "None" },
  { value: "Rock", label: "Rock" },
  { value: "Pop", label: "Pop" },
  { value: "Hip-Hop", label: "Hip-Hop" },
  { value: "Electronic", label: "Electronic" },
  { value: "Country", label: "Country" },
  { value: "Latin", label: "Latin" },
  { value: "Reggae", label: "Reggae" },
  { value: "Jazz", label: "Jazz" },
  { value: "Blues", label: "Blues" },
  { value: "Soul", label: "Soul" },
  { value: "Funk", label: "Funk" },
  { value: "R&B", label: "R&B" },
  { value: "Punk", label: "Punk" },
  { value: "Metal", label: "Metal" },
  { value: "Post-Rock", label: "Post-Rock" },
  { value: "Folk", label: "Folk" },
  { value: "Indie", label: "Indie" },
  { value: "Alternative", label: "Alternative" },
  { value: "Experimental", label: "Experimental" },
  { value: "Classical", label: "Classical" },
];
