import type { Profile, SocialField } from "@/lib/db/types";

const joined = (month: number, day: number, year: number) =>
  new Date(year, month - 1, day);

const social = (url = "", show = true): SocialField => ({ url, show });

export const mockProfiles: Profile[] = [
  {
    id: 2,
    profileName: "Neon Harbor",
    fullName: "Maya Chen",
    contactEmail: "maya@neonharbor.fm",
    bio: "Synth-pop producer blending city-night atmospheres with hook-driven choruses.",
    genre: "Synth Pop",
    joinedDate: joined(3, 12, 2024),
    isVerified: true,
    songClips: [
      { slot: 0, id: "101" },
      { slot: 1, id: "102" },
      { slot: 2, id: "103" },
    ],
    imageUrl: null,
    formattedLocation: "Los Angeles, CA, USA",
    city: "Los Angeles",
    country: "United States",
    countryCode: "us",
    state: "",
    stateCode: "CA",
    lat: 34,
    lon: -118,
    location: "POINT(-118 34)",
    website: social("https://neonharbor.fm"),
    facebook: social(),
    instagram: social("https://instagram.com/neonharbor"),
    tiktok: social("https://tiktok.com/@neonharbor"),
    spotify: social("https://open.spotify.com/artist/neonharbor"),
    appleMusic: social(),
    soundcloud: social("https://soundcloud.com/neonharbor"),
    bandcamp: social("https://neonharbor.bandcamp.com"),
    userRefId: "a1000001-0000-4000-8000-000000000001",
  },
  {
    id: 4,
    profileName: "Ridge & Rust",
    fullName: "Jonah Pike",
    contactEmail: "jonah@ridgeandrust.com",
    bio: "Americana songwriter focused on dusty vocals, lap steel, and road-worn storytelling.",
    genre: "Americana",
    joinedDate: joined(6, 2, 2023),
    isVerified: true,
    songClips: [
      { slot: 0, id: "201" },
      { slot: 1, id: "202" },
    ],
    imageUrl: null,
    formattedLocation: "Nashville, TN, USA",
    city: "Nashville",
    country: "United States",
    countryCode: "us",
    state: "",
    stateCode: "TN",
    lat: 36,
    lon: -87,
    location: "POINT(-87 36)",
    website: social("https://ridgeandrust.com"),
    facebook: social("https://facebook.com/ridgeandrust"),
    instagram: social("https://instagram.com/ridgeandrust"),
    tiktok: social(),
    spotify: social("https://open.spotify.com/artist/ridgeandrust"),
    appleMusic: social("https://music.apple.com/us/artist/ridge-and-rust"),
    soundcloud: social(),
    bandcamp: social("https://ridgeandrust.bandcamp.com"),
    userRefId: "a1000002-0000-4000-8000-000000000002",
  },
  {
    id: 5,
    profileName: "Kira Bloom",
    fullName: "Kira Bloom",
    contactEmail: "hello@kirabloom.music",
    bio: "R&B vocalist exploring soft falsetto textures and minimalist production.",
    genre: "R&B",
    joinedDate: joined(11, 18, 2024),
    isVerified: false,
    songClips: [{ slot: 0, id: "301" }],
    imageUrl: null,
    formattedLocation: "Atlanta, GA, USA",
    city: "Atlanta",
    country: "United States",
    countryCode: "us",
    state: "",
    stateCode: "GA",
    lat: 34,
    lon: -84,
    location: "POINT(-84 34)",
    website: social(),
    facebook: social(),
    instagram: social("https://instagram.com/kirabloom"),
    tiktok: social("https://tiktok.com/@kirabloom"),
    spotify: social("https://open.spotify.com/artist/kirabloom"),
    appleMusic: social(),
    soundcloud: social("https://soundcloud.com/kirabloom"),
    bandcamp: social("https://kirabloom.bandcamp.com"),
    userRefId: "a1000003-0000-4000-8000-000000000003",
  },
  {
    id: 6,
    profileName: "Static Garden",
    fullName: "Elliot Reyes",
    contactEmail: "elliot@staticgarden.io",
    bio: "Experimental electronic artist building glitchy beats from field recordings.",
    genre: "Electronic",
    joinedDate: joined(1, 9, 2025),
    isVerified: true,
    songClips: [
      { slot: 0, id: "401" },
      { slot: 1, id: "402" },
      { slot: 2, id: "403" },
    ],
    imageUrl: null,
    formattedLocation: "Brooklyn, NY, USA",
    city: "Brooklyn",
    country: "United States",
    countryCode: "us",
    state: "",
    stateCode: "NY",
    lat: 41,
    lon: -74,
    location: "POINT(-74 41)",
    website: social("https://staticgarden.io"),
    facebook: social(),
    instagram: social(),
    tiktok: social(),
    spotify: social("https://open.spotify.com/artist/staticgarden"),
    appleMusic: social(),
    soundcloud: social("https://soundcloud.com/staticgarden"),
    bandcamp: social("https://staticgarden.bandcamp.com"),
    userRefId: "a1000004-0000-4000-8000-000000000004",
  },
  {
    id: 7,
    profileName: "Marlowe Keys",
    fullName: "Marlowe Keys",
    contactEmail: "booking@marlowekeys.com",
    bio: "Jazz pianist composing cinematic instrumentals for late-night listening.",
    genre: "Jazz",
    joinedDate: joined(9, 4, 2022),
    isVerified: true,
    songClips: [
      { slot: 0, id: "501" },
      { slot: 2, id: "503" },
    ],
    imageUrl: null,
    formattedLocation: "Chicago, IL, USA",
    city: "Chicago",
    country: "United States",
    countryCode: "us",
    state: "",
    stateCode: "IL",
    lat: 42,
    lon: -88,
    location: "POINT(-88 42)",
    website: social("https://marlowekeys.com"),
    facebook: social("https://facebook.com/marlowekeys"),
    instagram: social("https://instagram.com/marlowekeys"),
    tiktok: social(),
    spotify: social("https://open.spotify.com/artist/marlowekeys"),
    appleMusic: social("https://music.apple.com/us/artist/marlowe-keys"),
    soundcloud: social(),
    bandcamp: social("https://marlowekeys.bandcamp.com"),
    userRefId: "a1000005-0000-4000-8000-000000000005",
  },
  {
    id: 8,
    profileName: "Dusty Parlor",
    fullName: "Amelia Hart",
    contactEmail: "amelia@dustyparlor.co",
    bio: "Indie folk duo writing harmony-heavy songs about small towns and slow summers.",
    genre: "Indie Folk",
    joinedDate: joined(4, 21, 2023),
    isVerified: false,
    songClips: [],
    imageUrl: null,
    formattedLocation: "Portland, OR, USA",
    city: "Portland",
    country: "United States",
    countryCode: "us",
    state: "",
    stateCode: "OR",
    lat: 46,
    lon: -123,
    location: "POINT(-123 46)",
    website: social("https://dustyparlor.co"),
    facebook: social(),
    instagram: social("https://instagram.com/dustyparlor"),
    tiktok: social("https://tiktok.com/@dustyparlor"),
    spotify: social("https://open.spotify.com/artist/dustyparlor"),
    appleMusic: social(),
    soundcloud: social("https://soundcloud.com/dustyparlor"),
    bandcamp: social("https://dustyparlor.bandcamp.com"),
    userRefId: "a1000006-0000-4000-8000-000000000006",
  },
  {
    id: 9,
    profileName: "Vanta Pulse",
    fullName: "Theo Nakamura",
    contactEmail: "theo@vantapulse.net",
    bio: "Industrial hip-hop producer pairing distorted drums with sharp, narrative bars.",
    genre: "Hip Hop",
    joinedDate: joined(7, 30, 2024),
    isVerified: true,
    songClips: [
      { slot: 0, id: "701" },
      { slot: 1, id: "702" },
      { slot: 2, id: "703" },
    ],
    imageUrl: null,
    formattedLocation: "Detroit, MI, USA",
    city: "Detroit",
    country: "United States",
    countryCode: "us",
    state: "",
    stateCode: "MI",
    lat: 42,
    lon: -83,
    location: "POINT(-83 42)",
    website: social(),
    facebook: social(),
    instagram: social("https://instagram.com/vantapulse"),
    tiktok: social("https://tiktok.com/@vantapulse"),
    spotify: social("https://open.spotify.com/artist/vantapulse"),
    appleMusic: social(),
    soundcloud: social("https://soundcloud.com/vantapulse"),
    bandcamp: social("https://vantapulse.bandcamp.com"),
    userRefId: "a1000007-0000-4000-8000-000000000007",
  },
  {
    id: 10,
    profileName: "Coral Cast",
    fullName: "Priya Menon",
    contactEmail: "priya@coralcast.live",
    bio: "Dream pop vocalist layering airy guitars and reverb-drenched vocal stacks.",
    genre: "Dream Pop",
    joinedDate: joined(2, 14, 2025),
    isVerified: true,
    songClips: [{ slot: 1, id: "802" }],
    imageUrl: null,
    formattedLocation: "Austin, TX, USA",
    city: "Austin",
    country: "United States",
    countryCode: "us",
    state: "",
    stateCode: "TX",
    lat: 30,
    lon: -98,
    location: "POINT(-98 30)",
    website: social("https://coralcast.live"),
    facebook: social(),
    instagram: social("https://instagram.com/coralcast"),
    tiktok: social(),
    spotify: social("https://open.spotify.com/artist/coralcast"),
    appleMusic: social("https://music.apple.com/us/artist/coral-cast"),
    soundcloud: social(),
    bandcamp: social("https://coralcast.bandcamp.com"),
    userRefId: "a1000008-0000-4000-8000-000000000008",
  },
  {
    id: 11,
    profileName: "Low Tide Choir",
    fullName: "Ben & Wren Alvarez",
    contactEmail: "ben@lowtidechoir.com",
    bio: "Coastal rock band mixing surf rhythms with baritone harmonies and analog grit.",
    genre: "Rock",
    joinedDate: joined(8, 7, 2023),
    isVerified: false,
    songClips: [
      { slot: 0, id: "901" },
      { slot: 1, id: "902" },
    ],
    imageUrl: null,
    formattedLocation: "San Diego, CA, USA",
    city: "San Diego",
    country: "United States",
    countryCode: "us",
    state: "",
    stateCode: "CA",
    lat: 33,
    lon: -117,
    location: "POINT(-117 33)",
    website: social("https://lowtidechoir.com"),
    facebook: social("https://facebook.com/lowtidechoir"),
    instagram: social("https://instagram.com/lowtidechoir"),
    tiktok: social("https://tiktok.com/@lowtidechoir"),
    spotify: social("https://open.spotify.com/artist/lowtidechoir"),
    appleMusic: social(),
    soundcloud: social("https://soundcloud.com/lowtidechoir"),
    bandcamp: social("https://lowtidechoir.bandcamp.com"),
    userRefId: "a1000009-0000-4000-8000-000000000009",
  },
  {
    id: 12,
    profileName: "North Arc",
    fullName: "Sofia Lindstrom",
    contactEmail: "sofia@northarc.se",
    bio: "Scandinavian pop producer crafting icy synth layers and crisp vocal toplines.",
    genre: "Pop",
    joinedDate: joined(12, 1, 2024),
    isVerified: true,
    songClips: [
      { slot: 0, id: "1001" },
      { slot: 1, id: "1002" },
      { slot: 2, id: "1003" },
    ],
    imageUrl: null,
    formattedLocation: "Stockholm, SE",
    city: "Stockholm",
    country: "SE",
    countryCode: "",
    state: "",
    stateCode: "SE",
    lat: 59,
    lon: 18,
    location: "POINT(18 59)",
    website: social("https://northarc.se"),
    facebook: social(),
    instagram: social("https://instagram.com/northarc"),
    tiktok: social("https://tiktok.com/@northarc"),
    spotify: social("https://open.spotify.com/artist/northarc"),
    appleMusic: social("https://music.apple.com/us/artist/north-arc"),
    soundcloud: social(),
    bandcamp: social("https://northarc.bandcamp.com"),
    userRefId: "a1000010-0000-4000-8000-000000000010",
  },
];
