import type { Profile } from "@/lib/db/types";

const joined = (month: number, day: number, year: number) =>
  new Date(year, month - 1, day);

export const mockProfiles: Profile[] = [
  {
    id: 2,
    profileName: "Neon Harbor",
    fullName: "Maya Chen",
    contactEmail: "maya@neonharbor.fm",
    bio: "Synth-pop producer blending city-night atmospheres with hook-driven choruses.",
    genre: "Synth Pop",
    joinedDate: joined(3, 12, 2024),
    isVerified: true,
    songClips: [
      { slot: 0, id: "101" },
      { slot: 1, id: "102" },
      { slot: 2, id: "103" },
    ],
    imageUrl: null,
    city: "Los Angeles",
    state: "CA",
    country: "US",
    website: "https://neonharbor.fm",
    facebook: null,
    instagram: "https://instagram.com/neonharbor",
    tiktok: "https://tiktok.com/@neonharbor",
    spotify: "https://open.spotify.com/artist/neonharbor",
    appleMusic: null,
    soundcloud: "https://soundcloud.com/neonharbor",
    bandcamp: "https://neonharbor.bandcamp.com",
    userRefId: "a1000001-0000-4000-8000-000000000001",
  },
  {
    id: 4,
    profileName: "Ridge & Rust",
    fullName: "Jonah Pike",
    contactEmail: "jonah@ridgeandrust.com",
    bio: "Americana songwriter focused on dusty vocals, lap steel, and road-worn storytelling.",
    genre: "Americana",
    joinedDate: joined(6, 2, 2023),
    isVerified: true,
    songClips: [
      { slot: 0, id: "201" },
      { slot: 1, id: "202" },
    ],
    imageUrl: null,
    city: "Nashville",
    state: "TN",
    country: "US",
    website: "https://ridgeandrust.com",
    facebook: "https://facebook.com/ridgeandrust",
    instagram: "https://instagram.com/ridgeandrust",
    tiktok: null,
    spotify: "https://open.spotify.com/artist/ridgeandrust",
    appleMusic: "https://music.apple.com/us/artist/ridge-and-rust",
    soundcloud: null,
    bandcamp: "https://ridgeandrust.bandcamp.com",
    userRefId: "a1000002-0000-4000-8000-000000000002",
  },
  {
    id: 5,
    profileName: "Kira Bloom",
    fullName: "Kira Bloom",
    contactEmail: "hello@kirabloom.music",
    bio: "R&B vocalist exploring soft falsetto textures and minimalist production.",
    genre: "R&B",
    joinedDate: joined(11, 18, 2024),
    isVerified: false,
    songClips: [{ slot: 0, id: "301" }],
    imageUrl: null,
    city: "Atlanta",
    state: "GA",
    country: "US",
    website: null,
    facebook: null,
    instagram: "https://instagram.com/kirabloom",
    tiktok: "https://tiktok.com/@kirabloom",
    spotify: "https://open.spotify.com/artist/kirabloom",
    appleMusic: null,
    soundcloud: "https://soundcloud.com/kirabloom",
    bandcamp: "https://kirabloom.bandcamp.com",
    userRefId: "a1000003-0000-4000-8000-000000000003",
  },
  {
    id: 6,
    profileName: "Static Garden",
    fullName: "Elliot Reyes",
    contactEmail: "elliot@staticgarden.io",
    bio: "Experimental electronic artist building glitchy beats from field recordings.",
    genre: "Electronic",
    joinedDate: joined(1, 9, 2025),
    isVerified: true,
    songClips: [
      { slot: 0, id: "401" },
      { slot: 1, id: "402" },
      { slot: 2, id: "403" },
    ],
    imageUrl: null,
    city: "Brooklyn",
    state: "NY",
    country: "US",
    website: "https://staticgarden.io",
    facebook: null,
    instagram: null,
    tiktok: null,
    spotify: "https://open.spotify.com/artist/staticgarden",
    appleMusic: null,
    soundcloud: "https://soundcloud.com/staticgarden",
    bandcamp: "https://staticgarden.bandcamp.com",
    userRefId: "a1000004-0000-4000-8000-000000000004",
  },
  {
    id: 7,
    profileName: "Marlowe Keys",
    fullName: "Marlowe Keys",
    contactEmail: "booking@marlowekeys.com",
    bio: "Jazz pianist composing cinematic instrumentals for late-night listening.",
    genre: "Jazz",
    joinedDate: joined(9, 4, 2022),
    isVerified: true,
    songClips: [
      { slot: 0, id: "501" },
      { slot: 2, id: "503" },
    ],
    imageUrl: null,
    city: "Chicago",
    state: "IL",
    country: "US",
    website: "https://marlowekeys.com",
    facebook: "https://facebook.com/marlowekeys",
    instagram: "https://instagram.com/marlowekeys",
    tiktok: null,
    spotify: "https://open.spotify.com/artist/marlowekeys",
    appleMusic: "https://music.apple.com/us/artist/marlowe-keys",
    soundcloud: null,
    bandcamp: "https://marlowekeys.bandcamp.com",
    userRefId: "a1000005-0000-4000-8000-000000000005",
  },
  {
    id: 8,
    profileName: "Dusty Parlor",
    fullName: "Amelia Hart",
    contactEmail: "amelia@dustyparlor.co",
    bio: "Indie folk duo writing harmony-heavy songs about small towns and slow summers.",
    genre: "Indie Folk",
    joinedDate: joined(4, 21, 2023),
    isVerified: false,
    songClips: [],
    imageUrl: null,
    city: "Portland",
    state: "OR",
    country: "US",
    website: "https://dustyparlor.co",
    facebook: null,
    instagram: "https://instagram.com/dustyparlor",
    tiktok: "https://tiktok.com/@dustyparlor",
    spotify: "https://open.spotify.com/artist/dustyparlor",
    appleMusic: null,
    soundcloud: "https://soundcloud.com/dustyparlor",
    bandcamp: "https://dustyparlor.bandcamp.com",
    userRefId: "a1000006-0000-4000-8000-000000000006",
  },
  {
    id: 9,
    profileName: "Vanta Pulse",
    fullName: "Theo Nakamura",
    contactEmail: "theo@vantapulse.net",
    bio: "Industrial hip-hop producer pairing distorted drums with sharp, narrative bars.",
    genre: "Hip Hop",
    joinedDate: joined(7, 30, 2024),
    isVerified: true,
    songClips: [
      { slot: 0, id: "701" },
      { slot: 1, id: "702" },
      { slot: 2, id: "703" },
    ],
    imageUrl: null,
    city: "Detroit",
    state: "MI",
    country: "US",
    website: null,
    facebook: null,
    instagram: "https://instagram.com/vantapulse",
    tiktok: "https://tiktok.com/@vantapulse",
    spotify: "https://open.spotify.com/artist/vantapulse",
    appleMusic: null,
    soundcloud: "https://soundcloud.com/vantapulse",
    bandcamp: "https://vantapulse.bandcamp.com",
    userRefId: "a1000007-0000-4000-8000-000000000007",
  },
  {
    id: 10,
    profileName: "Coral Cast",
    fullName: "Priya Menon",
    contactEmail: "priya@coralcast.live",
    bio: "Dream pop vocalist layering airy guitars and reverb-drenched vocal stacks.",
    genre: "Dream Pop",
    joinedDate: joined(2, 14, 2025),
    isVerified: true,
    songClips: [{ slot: 1, id: "802" }],
    imageUrl: null,
    city: "Austin",
    state: "TX",
    country: "US",
    website: "https://coralcast.live",
    facebook: null,
    instagram: "https://instagram.com/coralcast",
    tiktok: null,
    spotify: "https://open.spotify.com/artist/coralcast",
    appleMusic: "https://music.apple.com/us/artist/coral-cast",
    soundcloud: null,
    bandcamp: "https://coralcast.bandcamp.com",
    userRefId: "a1000008-0000-4000-8000-000000000008",
  },
  {
    id: 11,
    profileName: "Low Tide Choir",
    fullName: "Ben & Wren Alvarez",
    contactEmail: "ben@lowtidechoir.com",
    bio: "Coastal rock band mixing surf rhythms with baritone harmonies and analog grit.",
    genre: "Rock",
    joinedDate: joined(8, 7, 2023),
    isVerified: false,
    songClips: [
      { slot: 0, id: "901" },
      { slot: 1, id: "902" },
    ],
    imageUrl: null,
    city: "San Diego",
    state: "CA",
    country: "US",
    website: "https://lowtidechoir.com",
    facebook: "https://facebook.com/lowtidechoir",
    instagram: "https://instagram.com/lowtidechoir",
    tiktok: "https://tiktok.com/@lowtidechoir",
    spotify: "https://open.spotify.com/artist/lowtidechoir",
    appleMusic: null,
    soundcloud: "https://soundcloud.com/lowtidechoir",
    bandcamp: "https://lowtidechoir.bandcamp.com",
    userRefId: "a1000009-0000-4000-8000-000000000009",
  },
  {
    id: 12,
    profileName: "North Arc",
    fullName: "Sofia Lindstrom",
    contactEmail: "sofia@northarc.se",
    bio: "Scandinavian pop producer crafting icy synth layers and crisp vocal toplines.",
    genre: "Pop",
    joinedDate: joined(12, 1, 2024),
    isVerified: true,
    songClips: [
      { slot: 0, id: "1001" },
      { slot: 1, id: "1002" },
      { slot: 2, id: "1003" },
    ],
    imageUrl: null,
    city: "Stockholm",
    state: null,
    country: "SE",
    website: "https://northarc.se",
    facebook: null,
    instagram: "https://instagram.com/northarc",
    tiktok: "https://tiktok.com/@northarc",
    spotify: "https://open.spotify.com/artist/northarc",
    appleMusic: "https://music.apple.com/us/artist/north-arc",
    soundcloud: null,
    bandcamp: "https://northarc.bandcamp.com",
    userRefId: "a1000010-0000-4000-8000-000000000010",
  },
];
